# Generated by Django 3.2.6 on 2021-10-04 13:09

import colorfield.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server_models', '0001_initial'),
        ('reactbackend', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUUID',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.TextField(default=users.models.generate_unique_uuid, unique=True)),
                ('experation_date', models.DateTimeField(default=datetime.datetime(2021, 10, 11, 13, 9, 8, 80355, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('validation_email_send', models.BooleanField(default=False)),
                ('validation_email_send_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('published_count', models.IntegerField(default=0)),
                ('avatar_color', colorfield.fields.ColorField(default='#bdbdbd', max_length=18)),
                ('private_data', models.ManyToManyField(blank=True, to='server_models.Issue')),
                ('votes', models.ManyToManyField(blank=True, to='reactbackend.Votes')),
            ],
        ),
    ]
