# Generated by Django 3.2.6 on 2021-08-11 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenuuid',
            name='experation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 18, 33, 31, 574154)),
        ),
    ]
