# Generated by Django 3.2.6 on 2021-12-10 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tokenuuid',
            name='experation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 13, 51, 25, 446108, tzinfo=utc)),
        ),
    ]
