# Generated by Django 3.1.7 on 2021-07-11 11:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_color',
            field=colorfield.fields.ColorField(default='#bdbdbd', max_length=18),
        ),
    ]
