# Generated by Django 3.2.6 on 2021-08-21 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_tokenuuid_experation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenuuid',
            name='experation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 21, 12, 42, 476546, tzinfo=utc)),
        ),
    ]
