# Generated by Django 4.0.4 on 2022-05-15 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211210_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenuuid',
            name='experation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 8, 34, 48, 870575, tzinfo=utc)),
        ),
    ]
