# Generated by Django 3.2.6 on 2021-08-11 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tokenuuid_experation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenuuid',
            name='experation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 18, 36, 49, 592331, tzinfo=utc)),
        ),
    ]
