# Generated by Django 3.2.6 on 2021-08-11 18:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tokenuuid_experation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='validation_email_send_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 11, 18, 37, 19, 678865, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tokenuuid',
            name='experation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 18, 37, 19, 690917, tzinfo=utc)),
        ),
    ]
