# Generated by Django 3.2.6 on 2021-08-11 18:37

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210811_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='validation_email_send_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tokenuuid',
            name='experation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 18, 37, 41, 626758, tzinfo=utc)),
        ),
    ]
