# Generated by Django 3.2.6 on 2021-08-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='applied_change',
            field=models.CharField(choices=[('IP', 'Invalid position'), ('NT', 'No trees near this entry')], default=('IP', 'Invalid position'), max_length=2),
        ),
    ]
