# Generated by Django 3.2.6 on 2021-08-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackend', '0002_votes_applied_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='applied_change',
            field=models.CharField(blank=True, choices=[('IP', 'Invalid position'), ('NT', 'No trees near this entry')], max_length=2, null=True),
        ),
    ]
