# Generated by Django 3.2.6 on 2021-08-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackend', '0003_alter_votes_applied_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='applied_change',
            field=models.CharField(blank=True, choices=[(0, 'Invalid position'), (1, 'No trees near this entry')], max_length=2, null=True),
        ),
    ]
